export const categoryData = [
  {
    id: 1,
    key: 'NATURE',
    name: '자연',
    imgUrl: '/icons/category/01_trees.png',
    selected: false,
  },
  {
    id: 2,
    key: 'NIGHT_VIEW',
    name: '야경',
    imgUrl: '/icons/category/02_moonStar.png',
    selected: false,
  },
  {
    id: 3,
    key: 'LAKE',
    name: '호수',
    imgUrl: '/icons/category/03_lake.png',
    selected: false,
  },
  {
    id: 4,
    key: 'CHERRY_BLOSSOM',
    name: '벚꽃',
    imgUrl: '/icons/category/04_cherryBlossoms.png',
    selected: false,
  },
  {
    id: 5,
    key: 'EXERCISE',
    name: '운동',
    imgUrl: '/icons/category/05_sneakers.png',
    selected: false,
  },
  {
    id: 6,
    key: 'FOOD',
    name: '음식',
    imgUrl: '/icons/category/06_bungeoppang.png',
    selected: false,
  },
  {
    id: 7,
    key: 'LOVER',
    name: '연인',
    imgUrl: '/icons/category/07_heart.png',
    selected: false,
  },
  {
    id: 8,
    key: 'CHILD',
    name: '가족',
    imgUrl: '/icons/category/08_kindergartenHat.png',
    selected: false,
  },
  {
    id: 9,
    key: 'PET_DOG',
    name: '반려견',
    imgUrl: '/icons/category/09_dog.png',
    selected: false,
  },
];
