enum ActionTypes {
  /* roadActionTypes */
  OPEN_IMAGE_DETAIL = 'OPEN_IMAGE_DETAIL',
  CLOSE_IMAGE_DETAIL = 'CLOSE_IMAGE_DETAIL',

  REQUEST_GET_ROAD = 'REQUEST_GET_ROAD',
  REQUEST_GET_ROAD_SUCCESS = 'REQUEST_GET_ROAD_SUCCESS',
  REQUEST_GET_ROAD_ERROR = 'REQUEST_GET_ROAD_ERROR',

  /* editActionTypes */
  SET_ROAD = 'SET_ROAD',
  SET_TITLE = 'SET_TITLE',
  ADD_HASHTAG = 'ADD_HASHTAG',
  REMOVE_HASHTAG = 'REMOVE_TAG',
}

export default ActionTypes;
